// <auto-generated />
using System;
using EFCore_Codefirst_17328.A_DAL.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EFCore_Codefirst_17328.Migrations
{
    [DbContext(typeof(DogManagerContext))]
    partial class DogManagerContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("EFCore_Codefirst_17328.A_DAL.Models.Dog", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<bool>("GioiTinh")
                        .HasColumnType("bit");

                    b.Property<string>("GiongCho")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HumanCMT")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TenCho")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Tuoi")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("HumanCMT");

                    b.ToTable("Dogs");
                });

            modelBuilder.Entity("EFCore_Codefirst_17328.A_DAL.Models.Human", b =>
                {
                    b.Property<string>("CMT")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("Address");

                    b.Property<bool>("GioiTinh")
                        .HasColumnType("bit");

                    b.Property<string>("SoDT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("Tuoi")
                        .HasColumnType("datetime2");

                    b.HasKey("CMT");

                    b.ToTable("Humans");
                });

            modelBuilder.Entity("EFCore_Codefirst_17328.A_DAL.Models.Dog", b =>
                {
                    b.HasOne("EFCore_Codefirst_17328.A_DAL.Models.Human", null)
                        .WithMany("Dogs")
                        .HasForeignKey("HumanCMT");
                });

            modelBuilder.Entity("EFCore_Codefirst_17328.A_DAL.Models.Human", b =>
                {
                    b.Navigation("Dogs");
                });
#pragma warning restore 612, 618
        }
    }
}
